version: "3.9"

services:
  # База данных.
  postgres:
    container_name: postgres
    image: postgres:16.0
    environment:
      POSTGRES_DB: tawt
      POSTGRES_USER: tawt_user
      POSTGRES_PASSWORD: tawt_password
    ports:
      - "5432:5432"
    volumes:
      - ${HOME}/dev-postgres/data/:/var/lib/postgres
    networks:
      - dev-network

  # Брокер сообщений RabbitMQ.
  message-broker:
    container_name: message-broker
    ports:
      - "5672:5672"
      - "15672:15672"
    build:
      context: .
      dockerfile: services/rabbitmq/build/Dockerfile
    volumes:
      - ${HOME}/dev-rabbitmq/data/:/var/lib/rabbitmq
      - ${HOME}/dev-rabbitmq/log/:/var/log/rabbitmq
    restart: no
    networks:
      - dev-network

  # Сервис отправки запросов в брокер.
  scheduler:
    container_name: scheduler
    ports:
      - "9808:9808"
    build:
      context: .
      dockerfile: services/scheduler/build/Dockerfile
    restart: no
    depends_on:
      - postgres
      - message-broker
    networks:
      - dev-network

  # Сервис отправки задач в планировщика.
  sender:
    container_name: sender
    ports:
      - "8808:8808"
    build:
      context: .
      dockerfile: services/sender/build/Dockerfile
    restart: no
    depends_on:
      - scheduler
    networks:
      - dev-network

  # Сервис обработки текста.
  tawt:
    container_name: tawt
    ports:
      - "30002:30002"
    build:
      context: .
      dockerfile: services/tawt/build/Dockerfile
    restart: no
    depends_on:
      - scheduler
    networks:
      - dev-network



networks:
  dev-network:
    driver: bridge