# Конфигурация точки доступа.
service:
  grpc_endpoint: 9808

# Конфигурация подключения к БД.
postgres:
  pg_host: postgres
  pg_port: 5432
  pg_user: tawt_user
  pg_password: tawt_password
  pg_name: tawt
  pg_auto_migrate: true

# Конфигуарция подключения к брокеру сообщений.
rabbitmq:
  url: amqp://guest:guest@message-broker:5672/
  reconnect_delay: 3000
  max_priority: 10

# Перечисление названий очередей.
queues:
  slow_queue: tawt_queue_slow
  fast_queue_prefix: tawt_queue_fast